# Generated by Django 4.1.2 on 2022-10-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('descricao', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Produtos',
                'db_table': 'nome',
                'ordering': ['nome'],
            },
        ),
    ]
