# Generated by Django 4.1.2 on 2022-10-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
