# Generated by Django 4.1.2 on 2022-10-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtosApp', '0002_produtos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
