# Generated by Django 4.1.2 on 2022-10-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtosApp', '0003_alter_produtos_descricao_alter_produtos_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
