# Generated by Django 4.1.2 on 2022-10-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtosApp', '0004_alter_produtos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
