version: "3"

services:
  banco-django:
    image: postgres:12.6
    container_name: banco-django
    restart: unless-stopped
    environment:
      POSTGRES_DB: backlog-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    networks:
          - dj-prod

  dj:
    container_name: dj
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - banco-django
    networks:
      - dj-prod
networks:
  dj-prod:
    driver: bridge